/* ============================================================================
   THE SHMIFTING ASSET REGISTRY

   One place that knows what artwork exists. Everything is a static import so
   Next.js gets intrinsic dimensions and a blur placeholder for free, and so a
   missing file fails the build instead of shipping a broken image.

   Generated by scripts/generate-assets.mjs (OpenAI) and compressed by
   scripts/optimize-assets.mjs. The wordmarks are cut from Golden Reference 02
   by scripts/extract-wordmark.py.

   Adding artwork: add it to ASSETS in generate-assets.mjs, run
   `npm run assets:generate && npm run assets:optimize`, then export it here.
   Never reach for an emoji or an icon pack instead (CLAUDE.md §9).
   ========================================================================= */

import heroHome from "@/public/assets/hero-home.webp";
import heroVote from "@/public/assets/hero-vote.webp";
import heroMenu from "@/public/assets/hero-menu.webp";
import heroProfile from "@/public/assets/hero-profile.webp";
import heroShifts from "@/public/assets/hero-shifts.webp";
import heroLocked from "@/public/assets/hero-locked.webp";
import heroEmpty from "@/public/assets/hero-empty.webp";

import flameLit from "@/public/assets/flame-lit.webp";
import flameUnlit from "@/public/assets/flame-unlit.webp";
import memoryVial from "@/public/assets/memory-vial.webp";
import pot from "@/public/assets/pot.webp";
import sunMorning from "@/public/assets/sun-morning.webp";
import sunHigh from "@/public/assets/sun-high.webp";
import moonEvening from "@/public/assets/moon-evening.webp";
import handGiving from "@/public/assets/hand-giving.webp";
import signpost from "@/public/assets/signpost.webp";
import vegTomato from "@/public/assets/veg-tomato.webp";
import vegGarlic from "@/public/assets/veg-garlic.webp";
import vegChili from "@/public/assets/veg-chili.webp";
import shoppingBag from "@/public/assets/shopping-bag.webp";
import eyeMark from "@/public/assets/eye-mark.webp";

export const HERO = {
  home: heroHome,
  vote: heroVote,
  menu: heroMenu,
  profile: heroProfile,
  shifts: heroShifts,
  locked: heroLocked,
  empty: heroEmpty,
} as const;

export const OBJECT = {
  flameLit,
  flameUnlit,
  memoryVial,
  pot,
  sunMorning,
  sunHigh,
  moonEvening,
  handGiving,
  signpost,
  vegTomato,
  vegGarlic,
  vegChili,
  shoppingBag,
  eyeMark,
} as const;

/* The desert clock (Design Book §22, §39) — which celestial object marks
   which part of the day. */
export const MEAL_ART = {
  breakfast: sunMorning,
  lunch: sunHigh,
  dinner: moonEvening,
  snack: eyeMark,
  prep: pot,
  cleanup: handGiving,
} as const;

export type HeroKey = keyof typeof HERO;
